// Buffy Next — Core Types
// All interfaces used across the project
// Includes backward-compatible aliases for pre-existing code

// ─── Platform ──────────────────────────────────────────────

export type PlatformName = 'windows' | 'android-termux' | 'linux';

export interface PlatformInfo {
  name: PlatformName;
  os: string;
  version: string;
  arch: string;
}

// ─── System ────────────────────────────────────────────────

/** Sub-types for backward compatibility (old android-termux.ts, etc.) */
export type OSInfo = { name: string; version: string; arch: string };
export type CPUInfo = { model: string; cores: number; usage?: number };
export type MemoryInfo = { totalGB: number; availableGB: number; usedPercent: number };
export type GPUInfo = { name: string; driver: string; isGeneric: boolean };
export type StorageInfo = { devices: StorageDevice[] };
export type TempInfo = { cpuCelsius: number };

export interface SystemInfo {
  os: OSInfo;
  cpu: CPUInfo;
  memory: MemoryInfo;
  gpu: GPUInfo;
  /** Storage devices — new code uses this array directly */
  storage: StorageDevice[];
  /** Backward compat: old code accesses system.storage.devices */
  devices?: StorageDevice[];
  temperature: TempInfo | null;
  processes: ProcessInfo[];
  /** Platform-level privileges detected at runtime */
  privileges?: PlatformCapabilities;
}

export interface StorageDevice {
  mount: string;
  totalGB: number;
  freeGB: number;
  usedPercent: number;
}

export interface ProcessInfo {
  pid: number;
  name: string;
  cpuPercent: number;
  memoryMB: number;
}

// ─── Capabilities ──────────────────────────────────────────

/** Platform-level privileges detected at runtime (read-only, never auto-elevated) */
export interface PlatformCapabilities {
  /** Basic shell access (Termux /proc, df, ps, etc.) */
  shell: boolean;
  /** Shizuku elevated shell via rish */
  shizuku: boolean;
  /** Full root access (su) */
  root: boolean;
  /** ADB connection available */
  adb: boolean;
}

export interface Capability {
  name: string;
  status: 'installed' | 'missing' | 'unknown';
  version?: string;
  /** Backward compat: old code uses description */
  description?: string;
}

// ─── Security ──────────────────────────────────────────────

export type SecurityLevel = 'auto_safe' | 'confirm' | 'forbidden';
/** Backward compat alias */
export type ActionLevel = SecurityLevel;
export type DiagnosticSeverity = CheckResult['severity'];
export type CheckName = string;

// ─── Actions ───────────────────────────────────────────────

export interface ActionDefinition {
  id: string;
  name: string;
  description: string;
  level: SecurityLevel;
  reversible: boolean;
  rollback?: () => Promise<void>;
  /** Backward compat: old code uses verify */
  verify?: () => Promise<boolean>;
  platforms: PlatformName[];
  prerequisites: string[];
  execute: () => Promise<ActionResult>;
  dryRun?: () => Promise<string>;
}

export interface ActionResult {
  success: boolean;
  message: string;
  details?: Record<string, unknown>;
}

// ─── Check Selector ────────────────────────────────────────

export interface CheckResult {
  id: string;
  category: string;
  severity: 'ok' | 'warning' | 'error' | 'unknown';
  message: string;
  suggestion?: string;
  /** Backward compat: old code uses explanation */
  explanation?: string;
  actionId?: string;
  /** Backward compat: old code uses suggestedAction */
  suggestedAction?: string;
}

/** Backward compat alias */
export type DiagnosticItem = CheckResult;

// ─── Diagnosis ─────────────────────────────────────────────

export interface DiagnosticResult {
  items: CheckResult[];
  suggestedActions: SuggestedAction[];
}

export interface SuggestedAction {
  action: ActionDefinition;
  reason: string;
}

export interface DoctorReport {
  platform: PlatformInfo;
  system: SystemInfo;
  capabilities: Capability[];
  privileges?: PlatformCapabilities;
  items: CheckResult[];
  timestamp: string;
}

// ─── State ─────────────────────────────────────────────────

export interface BuffyState {
  lastScan?: string;
  platform?: string;
  system?: Partial<SystemInfo>;
  actionHistory: ActionRecord[];
  /** Backward compat: old code uses preferences */
  preferences?: { language: string };
}

export interface ActionRecord {
  actionId: string;
  timestamp: string;
  success: boolean;
  message: string;
}

// ─── Context Package (对外 — consumed by external agents) ──

/**
 * BuffyContext — stable JSON contract for external consumers.
 * Generated by `buffy doctor --context`.
 *
 * Rules:
 *  - null = data not available on this platform (NOT 0, NOT "")
 *  - tools[].available = tool is functional/usable, not just binary found
 *  - schema is versioned; v2 may add fields, never remove
 *  - processes[], items[], checks are intentionally excluded
 */
export interface BuffyContext {
  /** Contract version — always present */
  schema: 'buffy.context/v1';

  /** Buffy version that generated this context */
  buffy_version: string;

  /** ISO 8601 timestamp */
  generated_at: string;

  /** Platform identification */
  platform: {
    /** Internal ID: 'windows' | 'android-termux' | 'linux' */
    os: string;
    /** Human-readable: "Windows 10 LTSC" / "Android" / "EndeavourOS" */
    os_name: string;
    /** OS version: "10.0.19045" / "13" / null if unavailable */
    os_version: string | null;
    /** Kernel version: "6.18.42-1-lts" / null if unavailable */
    kernel: string | null;
    /** Architecture: "x64" / "arm64-v8a" / "x86_64" */
    architecture: string;
  };

  /** Detected hardware */
  hardware: {
    /** CPU model: "AMD Ryzen 5 3400G" / "MT6765" / null */
    cpu: string | null;
    /** Physical cores */
    cpu_cores: number | null;
    /** Total RAM in GB */
    ram_gb: number | null;
    /** Available RAM in GB */
    ram_available_gb: number | null;
    /** GPU name: "Adreno 610" / "RX 550" / null */
    gpu: string | null;
    /** GPU driver: "amdgpu" / "27.20.12029.1000" / "bundled" / null */
    gpu_driver: string | null;
    /** Is this a generic/default driver? */
    gpu_is_generic: boolean | null;
    /** Storage devices */
    storage: Array<{
      mount: string;
      total_gb: number;
      free_gb: number;
      used_percent: number;
    }>;
    /** CPU temperature in °C, or null if unavailable */
    temperature_c: number | null;
  };

  /** Execution environment */
  environment: {
    /** Available shell: "bash" / "powershell" / "zsh" / null */
    shell: string | null;
    /** Node.js version */
    node_version: string | null;
  };

  /** Detected tools — available = functional/usable, not just binary found */
  tools: Array<{
    name: string;
    /** true = Buffy verified the tool works, not just that the binary exists */
    available: boolean;
    version: string | null;
  }>;

  /** Platform privileges detected at runtime */
  privileges: {
    /** Basic shell access */
    shell: boolean;
    /** Shizuku (rish) — Android only */
    shizuku: boolean;
    /** Full root access (su) */
    root: boolean;
    /** ADB connection available */
    adb: boolean;
  };
}

// ─── Exec utilities ────────────────────────────────────────

export interface ExecOptions {
  timeout?: number;
  cwd?: string;
  env?: Record<string, string>;
}

export interface ExecResult {
  exitCode: number;
  stdout: string;
  stderr: string;
  success: boolean;
}

// ─── Platform Adapter ──────────────────────────────────────

export interface PlatformAdapter {
  readonly name: string;

  /** Identificar plataforma */
  detect(): Promise<PlatformInfo>;

  /** Info del sistema (CPU, RAM, GPU, etc.) */
  systemInfo(): Promise<SystemInfo>;

  /** Herramientas disponibles en esta plataforma */
  capabilities(): Promise<Capability[]>;

  /** Ejecutar una acción definida */
  execute(action: ActionDefinition): Promise<ActionResult>;
}
